#!/bin/bash

# Months in English and Finnish
declare -a english=("January" "February" "March" "April" "May" "June" "July" "August" "September" "October" "November" "December")
declare -a finnish=("tammikuu" "helmikuu" "maaliskuu" "huhtikuu" "toukokuu" "kesäkuu" "heinäkuu" "elokuu" "syyskuu" "lokakuu" "marraskuu" "joulukuu")

for i in {0..11}; do
    month_num=$((i + 1))
    printf "%2d  %-12s %s\n" "$month_num" "${english[$i]}" "${finnish[$i]}"
done
